# Load all files in the "config" directory into a ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: pythonapp
  labels:
    {{- include "oidc-example.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "pythonapp/*").AsConfig . ) | indent 4 }}
